name: Format and Lint R Code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-r@v2

      - name: Install styler and lintr
        run: |
          install.packages(c('styler', 'lintr'))
        shell: Rscript {0}

      - name: Format R files
        run: |
          styler::style_dir("code")
        shell: Rscript {0}

      # Lint R files. The number of and specific errors will be displayed in the GitHub Actions logs under "Lint R files"
      - name: Lint R files
        run: |
          lint_results <- lintr::lint_dir("code")
          if (length(lint_results) > 0) {
            warning("Linting issues found:", call. = FALSE)
            print(lint_results)
          }
          cat("Number of possible errors:", length(lint_results), "\n")
        shell: Rscript {0}

# There are many errors in the /code.
      # You can also run the linter locally: 
      #   1. Go to your terminal and travel to the root of the project.
      #   2. Run the following command: Rscript -e "lintr::lint_dir('code')"
      # This will display all the linting problems in the /code directory.