name: Deploy to shinyapps.io

on:
  schedule:
    - cron: '10 16 * * 1/2'  # Every 2 weeks on Monday at 16:10 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
